### ISSUE TITLE
Error on formatting

### ISSUE THREAD

**Issue by pokey** [wenkokke/talonfmt#44] opened 2023-01-13 12:41 UTC
When formatting [this file](https://github.com/pokey/pokey_talon/blob/f1cd92d36034fa3591432a2720e1ec381f31ca66/apps/vscode/vscode.talon), I get the following error:

```
WARN Error: Traceback (most recent call last):
  File "/Users/pokey/.pyenv/versions/3.9.0/bin/talonfmt", line 8, in <module>
    sys.exit(cli())
  File "/Users/pokey/.pyenv/versions/3.9.0/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/pokey/.pyenv/versions/3.9.0/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/pokey/.pyenv/versions/3.9.0/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/pokey/.pyenv/versions/3.9.0/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/pokey/.pyenv/versions/3.9.0/lib/python3.9/site-packages/talonfmt/cli.py", line 177, in cli
    format_file(file_or_dir)
  File "/Users/pokey/.pyenv/versions/3.9.0/lib/python3.9/site-packages/talonfmt/cli.py", line 166, in format_file
    output = format(contents, encoding=encoding, filename=str(filename))
  File "/Users/pokey/.pyenv/versions/3.9.0/lib/python3.9/site-packages/talonfmt/cli.py", line 137, in format
    output = talonfmt(
  File "/Users/pokey/.pyenv/versions/3.9.0/lib/python3.9/site-packages/talonfmt/__init__.py", line 112, in talonfmt
    formatted = render(ast, verbose=True)
  File "/Users/pokey/.pyenv/versions/3.9.0/lib/python3.9/site-packages/talonfmt/__init__.py", line 109, in render
    doc = talon_formatter.format(ast)
  File "/Users/pokey/.pyenv/versions/3.9.0/lib/python3.9/functools.py", line 914, in _method
    return method.__get__(obj, cls)(*args, **kwargs)
  File "/Users/pokey/.pyenv/versions/3.9.0/lib/python3.9/site-packages/talonfmt/formatter.py", line 132, in format
    return cat(self.format_lines(node))
  File "/Users/pokey/.pyenv/versions/3.9.0/lib/python3.9/site-packages/doc_printer/doc.py", line 251, in cat
    docs = tuple(filter(bool, splat(doclike, unpack=Cat)))
  File "/Users/pokey/.pyenv/versions/3.9.0/lib/python3.9/site-packages/doc_printer/doc.py", line 242, in splat
    yield from splat(smaller_doclike, unpack=unpack)
  File "/Users/pokey/.pyenv/versions/3.9.0/lib/python3.9/site-packages/doc_printer/doc.py", line 241, in splat
    for smaller_doclike in doclike:
  File "/Users/pokey/.pyenv/versions/3.9.0/lib/python3.9/site-packages/talonfmt/formatter.py", line 232, in _
    yield from self.format_lines(child)
  File "/Users/pokey/.pyenv/versions/3.9.0/lib/python3.9/site-packages/talonfmt/formatter.py", line 144, in format_lines
    raise TypeError(type(node))
TypeError: <class 'abc.TalonDeclarations'>

    at ChildProcess.<anonymous> (vscode-file://vscode-app/Users/pokey/.vscode/extensions/wenkokke.talonfmt-vscode-0.1.1/dist/extension.js:6:25837)
    at ChildProcess.emit (node:events:526:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

**Comment by wenkokke** [comment] 2023-01-13 13:22
What version of talonfmt are you using? Do you get any errors while running talonfmt from command line?

**Comment by pokey** [comment] 2023-01-13 14:16
> What version of talonfmt are you using?

talonfmt-1.7.4

> Do you get any errors while running talonfmt from command line?

Just checked, and yes, it happens from cli as well.  Shall we move this issue to https://github.com/wenkokke/talonfmt then?  I believe I don't have enough permissions here to move issue

**Comment by wenkokke** [comment] 2023-01-13 15:38
Does it still happen with 1.8.1?

**Comment by wenkokke** [comment] 2023-01-19 17:01
Closing as I cannot reproduce with the latest version.

**Closed as not planned** 2023-01-19 17:01 UTC
